Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
python3 -u train_adversary.py --nodes 200 --budget 8 --graph-pool-nbr 2 --train-graph-nbr 1 --valid-graph-nbr 1 --valid-with-nature False --edge-p 0.1 --main-method rl --train-episodes 2000 --valid-episodes 1 --rl-algor DDQN --nnVersion v1 --batch-size 8 --GAT-heads 8 --GAT-atten-layer 1 --GAT-out-atten-layer 1 --GAT-hid-dim '(16,)' --GAT-s-hid-dim '(16,)' --GAT-out-hid-dim '(1,)' --GAT-s-out-hid-dim '(1,)' --alpha 0.2 --logdir 10_1 --logtime 1119 --seed-nbr 1 --gamma 0.99 --lr 1e-4 >../pscr/log_5/10_1/logdir/1119.txt 2>../pscr/log_5/10_1/logdir/1119_error.txt &
Terminated
